---
- name: uninstall the iis web service
  hosts: windows

  tasks:
    - name: Close port for site on the firewall
      win_firewall_rule:
        name: "iisport 80"
        enable: no
        state: absent
        localport: "80"
        action: Allow
        direction: In
        protocol: Tcp

    - name: stop iis service
      win_service:
        name: W3Svc
        state: stopped

    - name: uninstall iis
      win_feature:
        name: Web-Server
        state: absent


