---
- name: Apache server uninstalled
  hosts: all

  tasks:

  - name: Apache uenabled and urunning
    service:
      name: httpd
      enabled: false
      state: stopped

  - name: firewalld upermits http service
    firewalld:
      service: http
      permanent: false
      state: disabled
      immediate: yes

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: false
      state: stopped

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: absent

  - name: latest Apache version installed
    yum:
      name: httpd
      state: absent
